version: "3"
services:
  backend:
    build: .    
    container_name: backend_time_tracker
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app    
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:    
    image: postgres:15.3    
    environment:
      - POSTGRES_DB=timetracker
      - POSTGRES_USER=backend
      - POSTGRES_PASSWORD=postgres     
    container_name: db_time_tracker    
    volumes:
      - pgdbdata:/var/lib/postgresql/data/

volumes:
  pgdbdata: 